local time = require "assets.manager.time"
local defrx=require "defrx.defrx"

function init(self)
	time.init(self)
	msg.post(".", "acquire_input_focus")
end


function on_message(self, message_id, message, sender)
	time.on_message(self, message_id, message, sender)
end

function on_input(self, action_id, action)
	if self.sleep and action_id==hash("touch") and action.pressed then
		defrx.notify("force_wake_up")
	end
end